const roasts = [
    "My grandma clicks faster, and she's taking a nap.",
  "Are you using a steering wheel to control your mouse?",
  "Error 404: Hand-eye coordination not found.",
  "You aim like a Stormtrooper.",
  "You have the reaction time of a tectonic plate.",
  "Is this your first time using a computer?",
  "Are you clicking with your elbows?",
  "Watching you try to catch me is physically painful.",
  "Just close the tab. No one has to know about this.",
  "You couldn't catch a cold, let alone this button.",
  "I'm moving at 1mph, what's your excuse?",
  "Try opening your eyes next time.",
  "I've seen glaciers move faster.",
  "Even a sloth is embarrassed for you right now.",
  "You are the reason they put instructions on shampoo bottles.",
  "Did you fall asleep holding the mouse?",
  "Your cursor is moving like it's stuck in molasses.",
  "Is your mouse on a leash?",
  "I'd tell you to aim better, but I don't think you know what that means.",
  "I'm not even moving fast, you're just that slow.",
  "Are we playing a game, or are you just giving your mouse a tour of the screen?",
  "Go ahead and take a breath. You look stressed.",
  "Maybe try playing on a touchscreen so you can just smash your hand on it.",
  "I've seen dead pixels more active than you."
]

const buttonTexts = [
    "Catch Me!",
    "Too Slow!",
    "Nope!",
    "Missed!",
    "Almost!",
    "Try Again!",
    "Come Here!",
    "Not Today!",
    "You Wish!",
    "Good Luck!"
]

const colors = [
    "#ef4444",
    "#3b82f6",
    "#22c55e",
    "#f59e0b",
    "#8b5cf6",
    "#ec4899",
    "#06b6d4",
    "#e11d48"
]

const finalRoasts = [
    "Wow, you finally clicked a button. Put that on your resume.",
  "Congratulations! Only took you half your lifespan.",
  "I let you win out of pity. Don't let it go to your head.",
  "Are you proud of yourself? Because you really shouldn't be.",
  "Great job. Your parents must be thrilled.",
  "You did it! Now please go outside.",
  "I hope you didn't break a sweat doing that.",
  "A toddler could have done that faster, but okay.",
  "You win! But at what cost to your dignity?",
  "Okay, you win. Please stop aggressively clicking.",
  "Wow, sheer dumb luck really does exist.",
  "My imaginary battery was dying anyway.",
  "You caught me. Was it worth the carpal tunnel?",
  "Took you long enough. I was getting bored.",
  "I tripped over a pixel. You didn't win, I lost.",
  "Congratulations, you are now the King of Useless Achievements.",
  "Fine, you win. Do you want a medal or a cookie?",
  "I guess even a broken clock is right twice a day.",
  "You caught it! Only a thousand attempts too late to be impressive.",
  "Round of applause for the absolute bare minimum!",
  "Okay, calm down, e-sports champion.",
  "You finally did it. The world is saved. Oh wait, no it isn't.",
  "I yielded because watching you struggle was getting depressing.",
  "You clicked a digital button. Do you feel fulfilled now?",
  "Your persistence is only outmatched by your lack of coordination.",
  "Hooray. You did a thing.",
  "Wow. Such speed. Much reflex.",
  "I'd clap, but I don't have hands.",
  "You won! Now go do something productive with your life.",
  "I'm reporting you for using an aimbot.",
  "You finally caught me. Now what?",
  "That was physically painful to watch, but congrats.",
  "I hope you stretched before doing all that flailing.",
  "You won. My expectations were low, but holy cow.",
  "Are we done now? Can I go home?",
  "A stunning display of perfectly average human capability.",
  "You caught me! Please don't frame this moment.",
  "Look at you, clicking things like a big kid!",
  "I surrender. Your erratic mouse flailing was too much for me.",
  "You won! I'm sure this will be the absolute highlight of your year.",
  "I ran out of screen space, that doesn't count.",
  "Congratulations on wasting exactly this much of your time.",
  "You got me. I'll be in my trailer.",
  "Okay, you win. I'll let you have this one.",
  "Wow, you really showed that inanimate digital button who's boss.",
  "Victory is yours. Now go ice your wrist.",
  "I gave up because your cursor smelled weird.",
  "You did it! Try not to pull a muscle celebrating.",
  "I’d ask for a rematch, but I can’t bear watching that again.",
  "Task failed successfully."
]